### ISSUE TITLE
Trying to built a report using this lib.

### ISSUE THREAD

**Issue by fmoudoute** [practical-data-science/gilfoyle#1]
Hi, I am trying to built a report from python using this library, but using the tiles:

1. Do we always have to add metric_value_before,
2. If yes, does that has to be last year data absolutely ? is there a way around please ?  
3. The introduction note on practica-data-science page says we can use charts as well, how can i do it please ? 
4. Last question please, can we have more than 1 page_metrics ?

Apologies but i am struggling to find much information on how t

o use the library. 
Thank you

**Comment by practical-data-science** [comment]
Thanks for your message. 

1. Yes, at present the code only supports showing a metric with a comparison. I'll make this optional in a future release. 
2. I've added a feature to 0.913 to support this. You can now compare any periods and change the comparison label to year, month, period, week, or whatever. 
3. Yes, you can add charts. These need to be saved to image and then passed to the `page_visualisation` argument. There's now an `example.py` file showing this. 
4. At present, this isn't supported. Please can you expand on what you want and I may see if I can add it?

If you run `pip3 install --upgrade gilfoyle` and check that you're using 0.913, you should find the new support added and the new example script to run. 

Thanks,
Matt

**Comment by fmoudoute** [comment]
Hi Matt,
1 - Thank you very much for your super fast response. I did a lot of research  and I found your solution was the most elegant, so I committed to using it. Is there a way even I could help remove the previous year change element? With it as it is, i would not be able to make a presentation with nice tiles.
2 - I will make the upgrade now.
3 - ok, I will give it a try right now.
4 - For this point, I was asking if we can have multiple lines of tiles basically.
Thank you 
Frantz

**Comment by practical-data-science** [comment]
Thanks for the clarification, Frantz. You can currently compare different
periods (i.e. week, month, year) and show the change, but you cannot
currently hide the change metrics. I'll make these optional in a
future release, and I'll add support for more metric tiles.

The other thing I have been working on, but have yet to finish, is the
ability to inject a custom template, so you can design your own pages and
populate them with your own variables.

Matt

**Comment by fmoudoute** [comment]
Hey Matt, that would be good. I am 100% happy to test it whenever you want. for now i will try to figure out a solution, since the previous period element is quite a constraint.

**Comment by practical-data-science** [comment]
@fmoudoute Hi Frank, I've just pushed a new version in which metric comparisons are now optional. See example.py for usage.

**Comment by fmoudoute** [comment]
Hi Matt, thank you for reacting super fast. It works, it looks good, and i understood so much on libraries by looking at this case. 
I guess, this is no longer an issue! :)

**Comment by flyandlure** [comment]
No problem. Thanks, Frank.

**Comment by fmoudoute** [comment]
I will play a bit more and let you know.

**Comment by fmoudoute** [comment]
Hi Matt,
Quick question for you please, I am trying to make a 2-column page, i
modified the template to use a div with class=row, and below two
columns with class=col-m-6. But for some reason, it does not work, and
returns the table one below each other.
Do you know if there are limitations during the conversion to PDF at this
stage please ?
thank you again,
Best regards
Frantz
Below is what i used: <div class="row">


    <div class="col-md-6">
        {% if page.page_commentary is defined and page.page_commentary
is not none %}
        <p class="commentary">{{ page.page_commentary }}</p>
        {% endif %}

        {% if page.page_visualisation is defined and
page.page_visualisation !='' %}
          <img src="{{ page.page_visualisation }}" width="100%" height="100%">
        {% endif %}
    </div>

    <div class="col-md-6">
        {% if page.page_dataframe is defined and page.page_dataframe !='' %}
          {{ page.page_dataframe }}
        {% endif %}
    </div>
  </div>

**Comment by practical-data-science** [comment]
Sorry for the slow reply. Not sure if you have tried this, but to debug the issue I would do the following: 

1. Set your export filename to have a .html suffix i.e. `pdf = report.Report(output='example.html)`.
2. Generate the report in HTML, rather than as a pdf, i.e. `pdf.create_report(payload, verbose=False, output='html')`.
3. Open the HTML file and check whether the CSS renders it to fit on a single page. 

There's a bit of CSS code in the template that forces the content to fit a page, so if your content goes outside this it will break the layout and won't render on a page when you export it as a PDF. I suspect it will be related to this. 

Alternatively, it could just be an issue with the underlying PDF generator code (it uses Weasyprint under the hood). The templates are made in Bulma which I found fairly reliable when rendering as PDF through Weasyprint, however, some things may not work as intended and you may need to tweak the HTML/CSS accordingly.
